// <auto-generated />
using System;
using KineMotion.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace KineMotion.Infrastructure.Migrations
{
    [DbContext(typeof(KineMotionDbContext))]
    [Migration("20260918011502_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("KineMotion.Core.Entities.Patient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly?>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("DiagnosisIcd10")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("TherapistId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TherapistId");

                    b.ToTable("patients", (string)null);
                });

            modelBuilder.Entity("KineMotion.Core.Entities.Prescription", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Exercise")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uuid");

                    b.Property<int>("TargetReps")
                        .HasColumnType("integer");

                    b.Property<double>("TargetRomDeg")
                        .HasColumnType("double precision");

                    b.Property<Guid>("TherapistId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PatientId", "Active");

                    b.ToTable("prescriptions", (string)null);
                });

            modelBuilder.Entity("KineMotion.Core.Entities.Session", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("EndedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PrescriptionId")
                        .HasColumnType("uuid");

                    b.Property<int>("RepsCompleted")
                        .HasColumnType("integer");

                    b.Property<DateTime>("StartedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("TherapistId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PatientId", "StartedAtUtc");

                    b.ToTable("sessions", (string)null);
                });

            modelBuilder.Entity("KineMotion.Core.Entities.Session", b =>
                {
                    b.OwnsMany("KineMotion.Core.ValueObjects.PoseFrame", "Frames", b1 =>
                        {
                            b1.Property<Guid>("SessionId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd();

                            b1.Property<double>("ElbowFlexionDeg");

                            b1.Property<double>("HandX");

                            b1.Property<double>("HandY");

                            b1.Property<double>("ShoulderAbductionDeg");

                            b1.Property<double>("TimestampMs");

                            b1.Property<double>("TrunkLeanDeg");

                            b1.HasKey("SessionId", "__synthesizedOrdinal");

                            b1.ToTable("sessions");

                            b1
                                .ToJson("Frames")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("SessionId");
                        });

                    b.Navigation("Frames");
                });
#pragma warning restore 612, 618
        }
    }
}
