// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using VitalFace.Infrastructure.Persistence;

#nullable disable

namespace VitalFace.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(VitalFaceDbContext))]
    partial class VitalFaceDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("VitalFace.Core.Models.Screening", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CriticalReasons")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<double>("FatigueScore")
                        .HasColumnType("double precision");

                    b.Property<double?>("HeartRateBpm")
                        .HasColumnType("double precision");

                    b.Property<bool>("IsCritical")
                        .HasColumnType("boolean");

                    b.Property<string>("LocationId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<double?>("RespiratoryRateBpm")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAtUtc");

                    b.HasIndex("LocationId");

                    b.ToTable("screenings", (string)null);
                });

            modelBuilder.Entity("VitalFace.Core.Models.Screening", b =>
                {
                    b.OwnsOne("VitalFace.Core.Models.ConsentRecord", "Consent", b1 =>
                        {
                            b1.Property<Guid>("ScreeningId")
                                .HasColumnType("uuid");

                            b1.Property<DateTimeOffset>("ConsentedAtUtc")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("consent_at_utc");

                            b1.Property<string>("SignatureHash")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("character varying(64)")
                                .HasColumnName("consent_signature_hash");

                            b1.HasKey("ScreeningId");

                            b1.ToTable("screenings");

                            b1.WithOwner()
                                .HasForeignKey("ScreeningId");
                        });

                    b.Navigation("Consent");
                });
#pragma warning restore 612, 618
        }
    }
}
